
version: "3.7"
services:
  flaskapp:
    restart: on-failure:50
    image: scm-booking-service:v2
    ports:
      - 5000:5000
    container_name: scm-booking-service
    environment:
      - APP_ENV=${APP_ENV}
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - scm-booking-service-net
    depends_on:
      - mongo
    logging:
      options:
        max-size: "100m"
        max-file: "30"
  mongo:
    restart: on-failure:50
    image: mongo:4.2
    ports:
      - 27017:27017
    networks:
      - scm-booking-service-net
    container_name: mongo
    volumes:
      - type: bind
        source: ./mongo_persistence
        target: /data/db

networks:
  scm-booking-service-net:
    driver: bridge
